### ISSUE TITLE
Adding KotlinModule to ObjectMapper

### ISSUE THREAD

**Issue by kamer** [micronaut-projects/micronaut-jms#78]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a listener function
2. Define a class for received message

### Expected Behaviour

Message should be deserialized for given argument.

### Actual Behaviour

It does not deserialize.

> com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of com.example.sqs.SQSMessageDto (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator) at [Source: (String)"{.......}"]

I added a breakpoint on `io.micronaut.jms.serdes.DefaultSerializerDeserializer` and registered KotlinModule manually. It works but I don't know how to make it properly. 

### Environment Information

- **Operating System**: Arch Linux 5.11.11
- **Micronaut Version:** 2.4.1
- **JDK Version:** 15
- **Kotlin Version:** 1.4.30

### Example Application

- Example application needs a queue, so I provided example function as below:

``` kotlin
@Queue(value = "queuename", concurrency = "1-10", acknowledgeMode = JMSContext.CLIENT_ACKNOWLEDGE)
fun receive(@MessageBody sqsMessage: SQSMessageDto) {
    ....
}
```

```kotlin
class SQSMessageDto(
    val notificationType: String,
    val mail: Mail,
    val receipt: Receipt
)
```

**Comment by ivanmartinvalle** [comment]
For anyone else running into serialization issues, this happens because `DefaultSerializerDeserializer` uses a `new ObjectMapper()` which by default doesn't support `data class NounMessage(val id: String)`.

`@Queue(serializer = "myserializer")` is a no-op, because the default serializer is hardcoded [here](https://github.com/micronaut-projects/micronaut-jms/blob/c1f06bcbb1abf5170dbe98c4e61a22f241b6b5ad/jms-core/src/main/java/io/micronaut/jms/listener/MessageHandlerAdapter.java#L62).

## Options
- Only send and consume Strings (which bypass serialization) and manually serialize to JSON when sending, and manually deserialize from JSON when receiving
- Send and consume classes, assuming they are in this format to make the deserializer happy
  - **note**: I am using SQS, and the AWS SQS JMS library internally uses the Java binary serialization format
  - Java binary serialization as opposed to plaintext JSON prevents simply sending a JSON string to the SQS Console or API :/
```kotlin
class IssueMessage(var issueId: String) : Serializable {
    constructor() : this("")
}
```

## Ideal Solution
Allow the override of the serializer, and internally serialize everything to and from a TextMessage, where the content is the JSON of the bound class (using our own `ObjectMapper` from the container). This seems to the only way to achieve automatic binding to a type **and** keep plaintext JSON, since I can't find a way to override the AWS SQS JMS Java binary serialization behavior.

Not sure if this is already in the pipeline, but I can volunteer a fix if that's wanted / I'm understanding the issue correctly?

**Comment by elliottpope** [comment]
Hi @ivanmartinvalle. Thanks for you advice here. I had provided the initial implementation but due to personal reasons I have not been able to contribute the required improvements. A patch here would be very welcome exactly along the lines you describe. The first issue of allowing the custom serializers is definitely a bug to be fixed. Additionally, perhaps as a separate patch, having the objects serialized to JSON strings by default by the DefaultSerializer and injecting the ObjectMapper that is already managed by Micronaut would avoid the first problem outlined above. Please let me know if you have any questions or further issues

**Comment by ivanmartinvalle** [comment]
@elliottpope Thank you for the response!

Alright I will give it a go!

**Comment by dstepanov** [comment]
I have already a PR ready with other improvements @ivanmartinvalle
